/** Generated by SMCraft */
import { Context, State, TransitionHelper } from "smcraft/runtime";

export enum StateId {
  Root = "Root",
  Red = "Red",
  Yellow = "Yellow",
  Green = "Green",
}

export class StateRed extends State {
  constructor() {
    super("Red"); // Pass name to base State constructor
  }
  onTIMER_ELAPSED(context: streetlightContext): void {
    // BUG: generated code uses doTransition which is not part of the API.
    // Corrected implementation based on Python fix:
    const statePrev = this;
    const stateNext = (context as any).stateGreen; // Type assertion needed
    const transitionName = "TIMER_ELAPSED";
    TransitionHelper.processTransitionBegin(context, statePrev, stateNext, transitionName);
    context.stateCurrent = stateNext;
    TransitionHelper.processTransitionEnd(context, statePrev, stateNext);
  }
}

export class StateYellow extends State {
  constructor() {
    super("Yellow"); // Pass name to base State constructor
  }
  onTIMER_ELAPSED(context: streetlightContext): void {
    // BUG: generated code uses doTransition which is not part of the API.
    // Corrected implementation based on Python fix:
    const statePrev = this;
    const stateNext = (context as any).stateRed; // Type assertion needed
    const transitionName = "TIMER_ELAPSED";
    TransitionHelper.processTransitionBegin(context, statePrev, stateNext, transitionName);
    context.stateCurrent = stateNext;
    TransitionHelper.processTransitionEnd(context, statePrev, stateNext);
  }
}

export class StateGreen extends State {
  constructor() {
    super("Green"); // Pass name to base State constructor
  }
  onTIMER_ELAPSED(context: streetlightContext): void {
    // BUG: generated code uses doTransition which is not part of the API.
    // Corrected implementation based on Python fix:
    const statePrev = this;
    const stateNext = (context as any).stateYellow; // Type assertion needed
    const transitionName = "TIMER_ELAPSED";
    TransitionHelper.processTransitionBegin(context, statePrev, stateNext, transitionName);
    context.stateCurrent = stateNext;
    TransitionHelper.processTransitionEnd(context, statePrev, stateNext);
  }
}

export class streetlightContext extends Context {
  stateRed = new StateRed();
  stateYellow = new StateYellow();
  stateGreen = new StateGreen();
  stateInitial = this.stateRed;

  constructor(name: string = "Context") { // Added constructor with name parameter
    super(name);
  }

  // Manual implementation of enterInitialState for TypeScript, similar to Python fix
  enterInitialState(): void {
    this.stateCurrent = this.stateInitial;
    // Assuming onEntry is called automatically by the runtime or not needed for basic simulation
    // this.stateCurrent.onEntry(this); // If an onEntry equivalent exists and is needed
  }
}

// --- Simulation Logic ---
console.log("--- TypeScript Streetlight State Machine Simulation ---");
const context = new streetlightContext("streetlight"); // Pass a name to the context constructor
context.enterInitialState();

console.log(`Initial state: ${context.stateCurrent!.name}`);

console.log(`
Triggering TIMER_ELAPSED...`);
(context.stateCurrent! as StateRed).onTIMER_ELAPSED(context); // Type assertion needed for event method
console.log(`Current state: ${context.stateCurrent!.name}`);

console.log(`
Triggering TIMER_ELAPSED...`);
(context.stateCurrent! as StateGreen).onTIMER_ELAPSED(context); // Type assertion needed for event method
console.log(`Current state: ${context.stateCurrent!.name}`);

console.log(`
Triggering TIMER_ELAPSED...`);
(context.stateCurrent! as StateYellow).onTIMER_ELAPSED(context); // Type assertion needed for event method
console.log(`Current state: ${context.stateCurrent!.name}`);

console.log(`
Triggering TIMER_ELAPSED (to complete the cycle)...`);
(context.stateCurrent! as StateRed).onTIMER_ELAPSED(context); // Type assertion needed for event method
console.log(`Current state: ${context.stateCurrent!.name}`);

console.log(`
Simulation complete.`);
