"""Generated by SMCraft"""
from enum import Enum, auto
from smcraft.runtime import Context, State, TransitionHelper

class StateId(Enum):
    Root = auto()
    Red = auto()
    Yellow = auto()
    Green = auto()

class StateRed(State):
    """State: Red"""
    def on_timer_elapsed(self, context):
        TransitionHelper.do_transition(context, context.state_green)

class StateYellow(State):
    """State: Yellow"""
    def on_timer_elapsed(self, context):
        TransitionHelper.do_transition(context, context.state_red)

class StateGreen(State):
    """State: Green"""
    def on_timer_elapsed(self, context):
        TransitionHelper.do_transition(context, context.state_yellow)

class streetlightContext(Context):
    """Context for streetlight"""
    def __init__(self):
        super().__init__()
        self.state_red = StateRed("Red")
        self.state_yellow = StateYellow("Yellow")
        self.state_green = StateGreen("Green")
        self.state_initial = self.state_red

# --- Simulation Logic ---
if __name__ == "__main__":
    print("--- Python Streetlight State Machine Simulation ---")
    context = streetlightContext()


    print(f"Initial state: {context.current_state.get_state_id().name}")

    print("\nTriggering TIMER_ELAPSED...")
    context.current_state.on_timer_elapsed(context)
    print(f"Current state: {context.current_state.get_state_id().name}")

    print("\nTriggering TIMER_ELAPSED...")
    context.current_state.on_timer_elapsed(context)
    print(f"Current state: {context.current_state.get_state_id().name}")

    print("\nTriggering TIMER_ELAPSED...")
    context.current_state.on_timer_elapsed(context)
    print(f"Current state: {context.current_state.get_state_id().name}")

    print("\nTriggering TIMER_ELAPSED (to complete the cycle)...")
    context.current_state.on_timer_elapsed(context)
    print(f"Current state: {context.current_state.get_state_id().name}")

    print("\nSimulation complete.")
