/** Generated by SMCraft */
import { Context, State, TransitionHelper } from "smcraft/runtime";

export enum StateId {
  Root = "Root",
  Idle = "Idle",
  Opening = "Opening",
  Active = "Active",
  Reflecting = "Reflecting",
  Closing = "Closing",
  Complete = "Complete",
}

export class StateIdle extends State {
  onBEGIN(context: CreativeSessionContext): void {
    TransitionHelper.doTransition(context, (context as any).stateOpening);
  }
}

export class StateOpening extends State {
  onINTENTIONS_SET(context: CreativeSessionContext): void {
    TransitionHelper.doTransition(context, (context as any).stateActive);
  }
}

export class StateActive extends State {
  onPAUSE(context: CreativeSessionContext): void {
    TransitionHelper.doTransition(context, (context as any).stateReflecting);
  }
  onCLOSE(context: CreativeSessionContext): void {
    TransitionHelper.doTransition(context, (context as any).stateClosing);
  }
}

export class StateReflecting extends State {
  onRESUME(context: CreativeSessionContext): void {
    TransitionHelper.doTransition(context, (context as any).stateActive);
  }
  onCLOSE(context: CreativeSessionContext): void {
    TransitionHelper.doTransition(context, (context as any).stateClosing);
  }
}

export class StateClosing extends State {
  onARCHIVE(context: CreativeSessionContext): void {
    TransitionHelper.doTransition(context, (context as any).stateComplete);
  }
}

export class StateComplete extends State {
}

export class CreativeSessionContext extends Context {
  stateIdle = new StateIdle();
  stateOpening = new StateOpening();
  stateActive = new StateActive();
  stateReflecting = new StateReflecting();
  stateClosing = new StateClosing();
  stateComplete = new StateComplete();
  stateInitial = this.stateIdle;
}
