"""Generated by SMCraft"""
from enum import Enum, auto
from smcraft.runtime import Context, State, TransitionHelper

class StateId(Enum):
    Root = auto()
    Idle = auto()
    Opening = auto()
    Active = auto()
    Reflecting = auto()
    Closing = auto()
    Complete = auto()

class StateIdle(State):
    """State: Idle"""
    def on_begin(self, context):
        TransitionHelper.do_transition(context, context.state_opening)

class StateOpening(State):
    """State: Opening"""
    def on_intentions_set(self, context):
        TransitionHelper.do_transition(context, context.state_active)

class StateActive(State):
    """State: Active"""
    def on_pause(self, context):
        TransitionHelper.do_transition(context, context.state_reflecting)
    def on_close(self, context):
        TransitionHelper.do_transition(context, context.state_closing)

class StateReflecting(State):
    """State: Reflecting"""
    def on_resume(self, context):
        TransitionHelper.do_transition(context, context.state_active)
    def on_close(self, context):
        TransitionHelper.do_transition(context, context.state_closing)

class StateClosing(State):
    """State: Closing"""
    def on_archive(self, context):
        TransitionHelper.do_transition(context, context.state_complete)

class StateComplete(State):
    """State: Complete"""

class CreativeSessionContext(Context):
    """Context for CreativeSession"""
    def __init__(self):
        super().__init__()
        self.state_idle = StateIdle()
        self.state_opening = StateOpening()
        self.state_active = StateActive()
        self.state_reflecting = StateReflecting()
        self.state_closing = StateClosing()
        self.state_complete = StateComplete()
        self.state_initial = self.state_idle
