#!/usr/bin/env bash
# live-loop.sh — one absolute source of truth for the real-time design loop.
#
# The defect this prevents: mcp/src/server.ts and web/src/lib/projectFile.ts
# each resolve SMCRAFT_PROJECT_FILE against their OWN cwd. Two processes,
# two cwds, one relative path → silent divergence that presents as "○ no disk".
# This launcher computes ABSOLUTE paths once and hands the same values to
# every process, and writes them to .env.smcraft-live for inspection.
#
# Usage:
#   scripts/live-loop.sh env        # print resolved exports (eval-able)
#   scripts/live-loop.sh hub        # start the socket hub (foreground)
#   scripts/live-loop.sh web-build  # build web with the bridge URL inlined
#   scripts/live-loop.sh web        # start the built web app (foreground)
#   scripts/live-loop.sh mcp-line   # print the MCP registration for claude
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

SMCRAFT_PROJECT_FILE="$(realpath -m "${SMCRAFT_PROJECT_FILE:-$ROOT/statemachine.smdf.json}")"
SMCRAFT_BRIDGE_HOST="${SMCRAFT_BRIDGE_HOST:-127.0.0.1}"
SMCRAFT_BRIDGE_PORT="${SMCRAFT_BRIDGE_PORT:-4599}"
SMCRAFT_BRIDGE_URL="${SMCRAFT_BRIDGE_URL:-http://${SMCRAFT_BRIDGE_HOST}:${SMCRAFT_BRIDGE_PORT}}"
export SMCRAFT_PROJECT_FILE SMCRAFT_BRIDGE_HOST SMCRAFT_BRIDGE_PORT SMCRAFT_BRIDGE_URL
export NEXT_PUBLIC_SMCRAFT_BRIDGE_URL="$SMCRAFT_BRIDGE_URL"

ENVFILE="$ROOT/.env.smcraft-live"
{
  echo "# generated by scripts/live-loop.sh — absolute values, both mcp and web read these"
  echo "SMCRAFT_PROJECT_FILE=$SMCRAFT_PROJECT_FILE"
  echo "SMCRAFT_BRIDGE_URL=$SMCRAFT_BRIDGE_URL"
  echo "NEXT_PUBLIC_SMCRAFT_BRIDGE_URL=$NEXT_PUBLIC_SMCRAFT_BRIDGE_URL"
} > "$ENVFILE"

case "${1:-env}" in
  env)
    echo "export SMCRAFT_PROJECT_FILE=$SMCRAFT_PROJECT_FILE"
    echo "export SMCRAFT_BRIDGE_URL=$SMCRAFT_BRIDGE_URL"
    echo "export NEXT_PUBLIC_SMCRAFT_BRIDGE_URL=$NEXT_PUBLIC_SMCRAFT_BRIDGE_URL"
    ;;
  hub)
    exec node "$ROOT/bridge/dist/bin.js" --host "$SMCRAFT_BRIDGE_HOST" --port "$SMCRAFT_BRIDGE_PORT"
    ;;
  web-build)
    # NEXT_PUBLIC_* is inlined at BUILD time — a running server cannot flip it.
    cd "$ROOT/web" && npm run build
    ;;
  web)
    cd "$ROOT/web" && npm run start 2>/dev/null || npx next start
    ;;
  mcp-line)
    echo "claude mcp add smcraft --env SMCRAFT_PROJECT_FILE=$SMCRAFT_PROJECT_FILE --env SMCRAFT_BRIDGE_URL=$SMCRAFT_BRIDGE_URL -- node $ROOT/mcp/dist/server.js"
    ;;
  *)
    echo "unknown subcommand: $1 (env|hub|web-build|web|mcp-line)" >&2
    exit 2
    ;;
esac
