#!/usr/bin/env bash
# live-loop.sh — one absolute source of truth for the real-time design loop.
#
# The defect this prevents: mcp/src/server.ts and web/src/lib/projectFile.ts
# each resolve the project file against their OWN cwd. Two processes,
# two cwds, one relative path → silent divergence that presents as "○ no disk".
# This launcher computes ABSOLUTE paths once and hands the same values to
# every process, and writes them to .env.smcraft-live for inspection.
#
# Env names: STATELOOM_* is read first; the SMCRAFT_* legacy twin is honored
# and BOTH twins are exported, so every process — old name or new — agrees.
# 4598 (web canvas) and 4599 (hub) sit together as the loom's pair of ports.
#
# Usage:
#   scripts/live-loop.sh env        # print resolved exports (eval-able)
#   scripts/live-loop.sh hub        # start the socket hub (foreground)
#   scripts/live-loop.sh web-build  # build web with the bridge URL inlined
#   scripts/live-loop.sh web        # start the built web app (foreground)
#   scripts/live-loop.sh mcp-line   # print the MCP registration for claude
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

STATELOOM_PROJECT_FILE="$(realpath -m "${STATELOOM_PROJECT_FILE:-${SMCRAFT_PROJECT_FILE:-$ROOT/statemachine.smdf.json}}")"
STATELOOM_BRIDGE_HOST="${STATELOOM_BRIDGE_HOST:-${SMCRAFT_BRIDGE_HOST:-127.0.0.1}}"
STATELOOM_BRIDGE_PORT="${STATELOOM_BRIDGE_PORT:-${SMCRAFT_BRIDGE_PORT:-4599}}"
STATELOOM_BRIDGE_URL="${STATELOOM_BRIDGE_URL:-${SMCRAFT_BRIDGE_URL:-http://${STATELOOM_BRIDGE_HOST}:${STATELOOM_BRIDGE_PORT}}}"
STATELOOM_WEB_PORT="${STATELOOM_WEB_PORT:-4598}"

# Legacy twins mirror the resolved values so both generations of readers agree.
SMCRAFT_PROJECT_FILE="$STATELOOM_PROJECT_FILE"
SMCRAFT_BRIDGE_HOST="$STATELOOM_BRIDGE_HOST"
SMCRAFT_BRIDGE_PORT="$STATELOOM_BRIDGE_PORT"
SMCRAFT_BRIDGE_URL="$STATELOOM_BRIDGE_URL"

export STATELOOM_PROJECT_FILE STATELOOM_BRIDGE_HOST STATELOOM_BRIDGE_PORT STATELOOM_BRIDGE_URL STATELOOM_WEB_PORT
export SMCRAFT_PROJECT_FILE SMCRAFT_BRIDGE_HOST SMCRAFT_BRIDGE_PORT SMCRAFT_BRIDGE_URL
export NEXT_PUBLIC_STATELOOM_BRIDGE_URL="$STATELOOM_BRIDGE_URL"
export NEXT_PUBLIC_SMCRAFT_BRIDGE_URL="$STATELOOM_BRIDGE_URL"

ENVFILE="$ROOT/.env.smcraft-live"
{
  echo "# generated by scripts/live-loop.sh — absolute values, both mcp and web read these"
  echo "STATELOOM_PROJECT_FILE=$STATELOOM_PROJECT_FILE"
  echo "STATELOOM_BRIDGE_URL=$STATELOOM_BRIDGE_URL"
  echo "STATELOOM_WEB_PORT=$STATELOOM_WEB_PORT"
  echo "NEXT_PUBLIC_STATELOOM_BRIDGE_URL=$NEXT_PUBLIC_STATELOOM_BRIDGE_URL"
  echo "SMCRAFT_PROJECT_FILE=$SMCRAFT_PROJECT_FILE"
  echo "SMCRAFT_BRIDGE_URL=$SMCRAFT_BRIDGE_URL"
  echo "NEXT_PUBLIC_SMCRAFT_BRIDGE_URL=$NEXT_PUBLIC_SMCRAFT_BRIDGE_URL"
} > "$ENVFILE"

case "${1:-env}" in
  env)
    echo "export STATELOOM_PROJECT_FILE=$STATELOOM_PROJECT_FILE"
    echo "export STATELOOM_BRIDGE_URL=$STATELOOM_BRIDGE_URL"
    echo "export STATELOOM_WEB_PORT=$STATELOOM_WEB_PORT"
    echo "export NEXT_PUBLIC_STATELOOM_BRIDGE_URL=$NEXT_PUBLIC_STATELOOM_BRIDGE_URL"
    echo "export SMCRAFT_PROJECT_FILE=$SMCRAFT_PROJECT_FILE"
    echo "export SMCRAFT_BRIDGE_URL=$SMCRAFT_BRIDGE_URL"
    echo "export NEXT_PUBLIC_SMCRAFT_BRIDGE_URL=$NEXT_PUBLIC_SMCRAFT_BRIDGE_URL"
    ;;
  hub)
    exec node "$ROOT/bridge/dist/bin.js" --host "$STATELOOM_BRIDGE_HOST" --port "$STATELOOM_BRIDGE_PORT"
    ;;
  web-build)
    # NEXT_PUBLIC_* is inlined at BUILD time — a running server cannot flip it.
    cd "$ROOT/web" && npm run build
    ;;
  web)
    cd "$ROOT/web" && PORT="$STATELOOM_WEB_PORT" npm run start 2>/dev/null \
      || PORT="$STATELOOM_WEB_PORT" npx next start -p "$STATELOOM_WEB_PORT"
    ;;
  mcp-line)
    echo "claude mcp add stateloom --env STATELOOM_PROJECT_FILE=$STATELOOM_PROJECT_FILE --env STATELOOM_BRIDGE_URL=$STATELOOM_BRIDGE_URL -- node $ROOT/mcp/dist/server.js"
    ;;
  *)
    echo "unknown subcommand: $1 (env|hub|web-build|web|mcp-line)" >&2
    exit 2
    ;;
esac
