#!/usr/bin/env node
/**
 * SMCraft MCP Server
 *
 * Provides tools for LLM agents to design, validate, and generate
 * state machines through conversation.
 *
 * Tools:
 *   - create_state_machine: Create a new state machine definition
 *   - add_state: Add a state to the definition
 *   - add_event: Add an event to the definition
 *   - add_transition: Add a transition to a state
 *   - remove_state: Remove a state from the definition
 *   - validate_definition: Validate the current definition
 *   - generate_code: Generate Python or TypeScript code
 *   - get_definition: Get the current definition as JSON
 *   - load_definition: Load a definition from JSON
 *   - list_states: List all states in the current definition
 *   - list_events: List all events in the current definition
 *
 * Resources:
 *   - smcraft://definition — Current state machine definition
 *
 * Prompts:
 *   - design-state-machine — Guided state machine design conversation
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

// ─── In-memory state machine definition ──────────────────────────────

interface StateDef {
  name: string;
  kind?: "normal" | "final" | "history";
  description?: string;
  transitions?: TransitionDef[];
  states?: StateDef[];
  onEntry?: string;
  onExit?: string;
}

interface TransitionDef {
  event: string;
  nextState?: string;
  condition?: string;
  description?: string;
}

interface EventDef {
  id: string;
  description?: string;
}

interface Definition {
  settings: {
    namespace: string;
    name: string;
    asynchronous: boolean;
  };
  events: { name: string; events: EventDef[] }[];
  state: StateDef;
}

let currentDefinition: Definition | null = null;

function createEmpty(namespace: string, name: string): Definition {
  return {
    settings: { namespace, name, asynchronous: false },
    events: [{ name: "Internal", events: [] }],
    state: { name: "Root", states: [] },
  };
}

function findState(root: StateDef, name: string): StateDef | null {
  if (root.name === name) return root;
  for (const child of root.states ?? []) {
    const found = findState(child, name);
    if (found) return found;
  }
  return null;
}

function removeState(root: StateDef, name: string): StateDef {
  return {
    ...root,
    states: root.states
      ?.filter((s) => s.name !== name)
      .map((s) => removeState(s, name)),
  };
}

function collectStateNames(root: StateDef): string[] {
  const names = [root.name];
  for (const child of root.states ?? []) {
    names.push(...collectStateNames(child));
  }
  return names;
}

function collectEventIds(def: Definition): string[] {
  return def.events.flatMap((src) => src.events.map((e) => e.id));
}

interface ValidationError {
  ruleId: string;
  message: string;
}

function validate(def: Definition): ValidationError[] {
  const errors: ValidationError[] = [];
  const stateNames = collectStateNames(def.state);
  const eventIds = collectEventIds(def);

  if (eventIds.length === 0) {
    errors.push({ ruleId: "V001", message: "No events defined" });
  }

  const seen = new Set<string>();
  for (const name of stateNames) {
    if (seen.has(name))
      errors.push({
        ruleId: "V002",
        message: `Duplicate state name: ${name}`,
      });
    seen.add(name);
  }

  const checkTransitions = (state: StateDef) => {
    for (const t of state.transitions ?? []) {
      if (!eventIds.includes(t.event))
        errors.push({
          ruleId: "V003",
          message: `State '${state.name}' references unknown event '${t.event}'`,
        });
      if (t.nextState && !stateNames.includes(t.nextState))
        errors.push({
          ruleId: "V004",
          message: `State '${state.name}' targets unknown state '${t.nextState}'`,
        });
    }
    (state.states ?? []).forEach(checkTransitions);
  };
  checkTransitions(def.state);

  if (!def.state.states || def.state.states.length === 0)
    errors.push({
      ruleId: "V005",
      message: "Root must have at least one child state",
    });

  return errors;
}

function generatePython(def: Definition): string {
  const lines: string[] = [];
  const name = def.settings.name ?? "StateMachine";
  const states = def.state.states ?? [];
  const events = collectEventIds(def);

  lines.push(`"""Generated by SMCraft"""`);
  lines.push(`from enum import Enum, auto`);
  lines.push(`from smcraft.runtime import Context, State, TransitionHelper`);
  lines.push(``);
  lines.push(`class StateId(Enum):`);
  for (const s of collectStateNames(def.state)) {
    lines.push(`    ${s} = auto()`);
  }
  lines.push(``);

  for (const s of states) {
    lines.push(`class State${s.name}(State):`);
    lines.push(`    """State: ${s.name}"""`);
    if (s.onEntry)
      lines.push(
        `    def on_entry(self, context):\n        ${s.onEntry}`
      );
    if (s.onExit)
      lines.push(
        `    def on_exit(self, context):\n        ${s.onExit}`
      );
    for (const t of s.transitions ?? []) {
      lines.push(`    def on_${t.event.toLowerCase()}(self, context):`);
      if (t.condition) lines.push(`        if not (${t.condition}): return`);
      if (t.nextState)
        lines.push(
          `        TransitionHelper.do_transition(context, context.state_${t.nextState.toLowerCase()})`
        );
      else lines.push(`        pass  # internal transition`);
    }
    lines.push(``);
  }

  lines.push(`class ${name}Context(Context):`);
  lines.push(`    """Context for ${name}"""`);
  lines.push(`    def __init__(self):`);
  lines.push(`        super().__init__()`);
  for (const s of states) {
    lines.push(
      `        self.state_${s.name.toLowerCase()} = State${s.name}()`
    );
  }
  lines.push(
    `        self.state_initial = self.state_${(states[0]?.name ?? "Root").toLowerCase()}`
  );
  lines.push(``);

  return lines.join("\n");
}

function generateTypeScript(def: Definition): string {
  const lines: string[] = [];
  const name = def.settings.name ?? "StateMachine";
  const states = def.state.states ?? [];

  lines.push(`/** Generated by SMCraft */`);
  lines.push(`import { Context, State, TransitionHelper } from "smcraft/runtime";`);
  lines.push(``);
  lines.push(`export enum StateId {`);
  for (const s of collectStateNames(def.state)) {
    lines.push(`  ${s} = "${s}",`);
  }
  lines.push(`}`);
  lines.push(``);

  for (const s of states) {
    lines.push(`export class State${s.name} extends State {`);
    for (const t of s.transitions ?? []) {
      lines.push(`  on${t.event}(context: ${name}Context): void {`);
      if (t.condition) lines.push(`    if (!(${t.condition})) return;`);
      if (t.nextState)
        lines.push(
          `    TransitionHelper.doTransition(context, (context as any).state${t.nextState});`
        );
      lines.push(`  }`);
    }
    lines.push(`}`);
    lines.push(``);
  }

  lines.push(`export class ${name}Context extends Context {`);
  for (const s of states) {
    lines.push(`  state${s.name} = new State${s.name}();`);
  }
  if (states.length > 0)
    lines.push(`  stateInitial = this.state${states[0].name};`);
  lines.push(`}`);

  return lines.join("\n");
}

// ─── MCP Server ──────────────────────────────────────────────────────

const server = new McpServer({
  name: "smcraft-mcp",
  version: "0.1.0",
});

// Tools

server.tool(
  "create_state_machine",
  "Create a new state machine definition with namespace and name",
  { namespace: z.string(), name: z.string(), asynchronous: z.boolean().optional() },
  async ({ namespace, name, asynchronous }) => {
    currentDefinition = createEmpty(namespace, name);
    if (asynchronous) currentDefinition.settings.asynchronous = true;
    return {
      content: [
        {
          type: "text",
          text: `Created state machine '${name}' in namespace '${namespace}'. Add states and events next.`,
        },
      ],
    };
  }
);

server.tool(
  "add_state",
  "Add a state to the state machine. Parent defaults to Root.",
  {
    name: z.string(),
    parent: z.string().optional(),
    kind: z.enum(["normal", "final", "history"]).optional(),
    description: z.string().optional(),
  },
  async ({ name, parent, kind, description }) => {
    if (!currentDefinition)
      return {
        content: [{ type: "text", text: "No state machine created yet. Use create_state_machine first." }],
        isError: true,
      };
    const parentName = parent ?? "Root";
    const parentState = findState(currentDefinition.state, parentName);
    if (!parentState)
      return {
        content: [{ type: "text", text: `Parent state '${parentName}' not found.` }],
        isError: true,
      };
    if (!parentState.states) parentState.states = [];
    parentState.states.push({ name, kind: kind ?? "normal", description });
    return {
      content: [{ type: "text", text: `Added state '${name}' under '${parentName}' (${kind ?? "normal"}).` }],
    };
  }
);

server.tool(
  "add_event",
  "Add an event to the state machine",
  { id: z.string(), description: z.string().optional() },
  async ({ id, description }) => {
    if (!currentDefinition)
      return {
        content: [{ type: "text", text: "No state machine created yet." }],
        isError: true,
      };
    const source = currentDefinition.events[0];
    source.events.push({ id, description });
    return {
      content: [{ type: "text", text: `Added event '${id}'.` }],
    };
  }
);

server.tool(
  "add_transition",
  "Add a transition to a state, triggered by an event",
  {
    state: z.string(),
    event: z.string(),
    nextState: z.string().optional(),
    condition: z.string().optional(),
    description: z.string().optional(),
  },
  async ({ state, event, nextState, condition, description }) => {
    if (!currentDefinition)
      return {
        content: [{ type: "text", text: "No state machine created yet." }],
        isError: true,
      };
    const target = findState(currentDefinition.state, state);
    if (!target)
      return {
        content: [{ type: "text", text: `State '${state}' not found.` }],
        isError: true,
      };
    if (!target.transitions) target.transitions = [];
    target.transitions.push({ event, nextState, condition, description });
    const desc = nextState ? `${state} --[${event}]--> ${nextState}` : `${state} --[${event}]--> (internal)`;
    return { content: [{ type: "text", text: `Added transition: ${desc}` }] };
  }
);

server.tool(
  "remove_state",
  "Remove a state from the definition",
  { name: z.string() },
  async ({ name }) => {
    if (!currentDefinition)
      return { content: [{ type: "text", text: "No state machine created yet." }], isError: true };
    if (name === "Root")
      return { content: [{ type: "text", text: "Cannot remove Root state." }], isError: true };
    currentDefinition.state = removeState(currentDefinition.state, name);
    return { content: [{ type: "text", text: `Removed state '${name}'.` }] };
  }
);

server.tool(
  "validate_definition",
  "Validate the current state machine definition against all rules",
  {},
  async () => {
    if (!currentDefinition)
      return { content: [{ type: "text", text: "No state machine created yet." }], isError: true };
    const errors = validate(currentDefinition);
    if (errors.length === 0)
      return { content: [{ type: "text", text: "✓ Definition is valid. No errors found." }] };
    const lines = errors.map((e) => `[${e.ruleId}] ${e.message}`).join("\n");
    return {
      content: [{ type: "text", text: `Found ${errors.length} validation error(s):\n${lines}` }],
    };
  }
);

server.tool(
  "generate_code",
  "Generate Python or TypeScript code from the current definition",
  { language: z.enum(["python", "typescript"]) },
  async ({ language }) => {
    if (!currentDefinition)
      return { content: [{ type: "text", text: "No state machine created yet." }], isError: true };
    const errors = validate(currentDefinition);
    if (errors.length > 0) {
      const lines = errors.map((e) => `[${e.ruleId}] ${e.message}`).join("\n");
      return {
        content: [{ type: "text", text: `Fix validation errors first:\n${lines}` }],
        isError: true,
      };
    }
    const code = language === "python" ? generatePython(currentDefinition) : generateTypeScript(currentDefinition);
    return { content: [{ type: "text", text: code }] };
  }
);

server.tool(
  "get_definition",
  "Get the current state machine definition as JSON",
  {},
  async () => {
    if (!currentDefinition)
      return { content: [{ type: "text", text: "No state machine created yet." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ stateMachine: currentDefinition }, null, 2) }],
    };
  }
);

server.tool(
  "load_definition",
  "Load a state machine definition from JSON",
  { json: z.string() },
  async ({ json }) => {
    try {
      const parsed = JSON.parse(json);
      currentDefinition = parsed.stateMachine ?? parsed.StateMachine ?? parsed;
      const stateCount = collectStateNames(currentDefinition!.state).length;
      const eventCount = collectEventIds(currentDefinition!).length;
      return {
        content: [
          {
            type: "text",
            text: `Loaded definition: ${currentDefinition!.settings.name} (${stateCount} states, ${eventCount} events)`,
          },
        ],
      };
    } catch (e) {
      return { content: [{ type: "text", text: `Invalid JSON: ${e}` }], isError: true };
    }
  }
);

server.tool(
  "list_states",
  "List all states in the current definition with their kind and transitions",
  {},
  async () => {
    if (!currentDefinition)
      return { content: [{ type: "text", text: "No state machine created yet." }], isError: true };
    const lines: string[] = [];
    const walk = (state: StateDef, depth: number) => {
      const indent = "  ".repeat(depth);
      const kind = state.kind ? ` (${state.kind})` : "";
      const transCount = state.transitions?.length ?? 0;
      lines.push(`${indent}${state.name}${kind} — ${transCount} transition(s)`);
      for (const t of state.transitions ?? []) {
        lines.push(`${indent}  → [${t.event}] → ${t.nextState ?? "(internal)"}`);
      }
      (state.states ?? []).forEach((s) => walk(s, depth + 1));
    };
    walk(currentDefinition.state, 0);
    return { content: [{ type: "text", text: lines.join("\n") }] };
  }
);

server.tool(
  "list_events",
  "List all events in the current definition",
  {},
  async () => {
    if (!currentDefinition)
      return { content: [{ type: "text", text: "No state machine created yet." }], isError: true };
    const events = currentDefinition.events.flatMap((src) =>
      src.events.map((e) => `${e.id}${e.description ? ` — ${e.description}` : ""}`)
    );
    if (events.length === 0)
      return { content: [{ type: "text", text: "No events defined yet." }] };
    return { content: [{ type: "text", text: events.join("\n") }] };
  }
);

// Resources

server.resource("definition", "smcraft://definition", async () => {
  return {
    contents: [
      {
        uri: "smcraft://definition",
        mimeType: "application/json",
        text: currentDefinition
          ? JSON.stringify({ stateMachine: currentDefinition }, null, 2)
          : '{"error": "No definition loaded"}',
      },
    ],
  };
});

// Prompts

server.prompt(
  "design-state-machine",
  "Guided conversation to design a state machine step by step",
  { domain: z.string().optional(), name: z.string().optional() },
  ({ domain, name }) => ({
    messages: [
      {
        role: "user",
        content: {
          type: "text",
          text: `I want to design a state machine${name ? ` called "${name}"` : ""}${domain ? ` for the "${domain}" domain` : ""}. Guide me through:
1. First, create the state machine with create_state_machine
2. Help me identify the key states and add them with add_state
3. Define the events that trigger transitions with add_event
4. Wire up transitions between states with add_transition
5. Validate the design with validate_definition
6. Generate code with generate_code

Start by asking me about the states and events I need.`,
        },
      },
    ],
  })
);

// Start

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("SMCraft MCP server running on stdio");
}

main().catch(console.error);
