/**
 * State Machine Code Generator — SMCG (Spec 62)
 *
 * Generates TypeScript state machine code from definitions.
 */

import type { EnrichedModel } from "./parser.js";
import type { EventDef, StateDef, TransitionDef, ActionDef } from "./model.js";

function toSnakeCase(name: string): string {
  return name
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .replace(/([a-z\d])([A-Z])/g, "$1_$2")
    .toLowerCase();
}

function toCamelCase(name: string): string {
  return name.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

function toPascalCase(name: string): string {
  const camel = toCamelCase(name);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

function toClassName(name: string): string {
  return name.replace(/[_\-\s]/g, "");
}

function tsType(type: string): string {
  const map: Record<string, string> = {
    string: "string",
    int: "number",
    float: "number",
    double: "number",
    bool: "boolean",
    boolean: "boolean",
    object: "unknown",
    Object: "unknown",
  };
  return map[type] ?? type;
}

export class TypeScriptCodeGenerator {
  private model: EnrichedModel;
  private settings;
  private lines: string[] = [];
  private indent = 0;

  constructor(model: EnrichedModel) {
    this.model = model;
    this.settings = model.definition.settings;
  }

  generate(): string {
    this.lines = [];
    this.emitHeader();
    this.emitImports();
    this.emitBlank();
    this.emitStateEnum();
    this.emitBlank();
    this.emitBaseStateClass();
    this.emitBlank();
    this.emitLeafStateClasses();
    this.emitContextClass();
    this.emitBlank();
    this.emitFeederClasses();
    return this.lines.join("\n");
  }

  private emitHeader(): void {
    const name = this.settings.name ?? "StateMachine";
    this.line(`/**`);
    this.line(` * Generated State Machine: ${name}`);
    this.line(` * Namespace: ${this.settings.namespace}`);
    this.line(` *`);
    this.line(` * Generated by SMCG. Do not edit manually.`);
    this.line(` */`);
    this.emitBlank();
  }

  private emitImports(): void {
    this.line(`import {`);
    this.line(`  Context,`);
    this.line(`  ContextAsync,`);
    this.line(`  ContextBase,`);
    this.line(`  ObserverNull,`);
    this.line(`  State,`);
    this.line(`  StateKind,`);
    this.line(`  TransitionHelper,`);
    this.line(`} from "./runtime.js";`);
  }

  private emitStateEnum(): void {
    const name = this.settings.name ?? "StateMachine";
    this.line(`export enum ${name}StateEnum {`);
    this.indent++;
    let idx = 0;
    for (const state of this.model.allStates) {
      if (state.kind === "history") continue;
      this.line(`${toSnakeCase(state.name).toUpperCase()} = ${idx},`);
      idx++;
    }
    this.indent--;
    this.line(`}`);
  }

  private emitBaseStateClass(): void {
    const name = this.settings.name ?? "StateMachine";
    this.line(`export class State${name} extends State {`);
    this.indent++;
    for (const [evtId, evt] of this.model.eventMap) {
      const params = this.buildParams(evt, true);
      const methodName = `on${toPascalCase(toSnakeCase(evtId))}`;
      this.line(`${methodName}(${params}): void {}`);
    }
    this.indent--;
    this.line(`}`);
  }

  private emitLeafStateClasses(): void {
    const name = this.settings.name ?? "StateMachine";
    for (const state of this.model.allStates) {
      if (state.kind === "history" || !this.isLeaf(state)) continue;
      this.emitStateClass(state, name);
      this.emitBlank();
    }
  }

  private emitStateClass(state: StateDef, machineName: string): void {
    const className = `State${toClassName(state.name)}`;
    const baseClass = `State${machineName}`;
    const kind = state.kind === "final" ? "StateKind.FINAL" : "StateKind.LEAF";

    this.line(`export class ${className} extends ${baseClass} {`);
    this.indent++;

    this.line(`constructor(parent: State | null = null) {`);
    this.indent++;
    this.line(`super("${state.name}", ${kind}, parent);`);
    this.indent--;
    this.line(`}`);
    this.emitBlank();

    // onEntry
    if (state.onEntry?.actions?.length) {
      this.line(`onEntry(context: ContextBase): void {`);
      this.indent++;
      for (const action of state.onEntry.actions) {
        this.emitAction(action, "context");
      }
      this.indent--;
      this.line(`}`);
      this.emitBlank();
    }

    // onExit
    if (state.onExit?.actions?.length) {
      this.line(`onExit(context: ContextBase): void {`);
      this.indent++;
      for (const action of state.onExit.actions) {
        this.emitAction(action, "context");
      }
      this.indent--;
      this.line(`}`);
      this.emitBlank();
    }

    // Group transitions by event
    const transitionsByEvent = new Map<string, TransitionDef[]>();
    for (const t of state.transitions ?? []) {
      if (!transitionsByEvent.has(t.event)) transitionsByEvent.set(t.event, []);
      transitionsByEvent.get(t.event)!.push(t);
    }

    for (const [eventId, transitions] of transitionsByEvent) {
      this.emitEventHandler(eventId, transitions);
    }

    this.indent--;
    this.line(`}`);
  }

  private emitEventHandler(eventId: string, transitions: TransitionDef[]): void {
    const evt = this.model.eventMap.get(eventId);
    if (!evt) return;

    const methodName = `on${toPascalCase(toSnakeCase(eventId))}`;
    const params = this.buildParams(evt, true);

    this.line(`${methodName}(${params}): void {`);
    this.indent++;

    for (let i = 0; i < transitions.length; i++) {
      const t = transitions[i];
      if (t.condition) {
        const kw = i === 0 ? "if" : "} else if";
        this.line(`${kw} (${t.condition}) {`);
        this.indent++;
        this.emitTransitionBody(t);
        this.indent--;
      } else if (transitions.length > 1 && i > 0) {
        this.line(`} else {`);
        this.indent++;
        this.emitTransitionBody(t);
        this.indent--;
      } else {
        this.emitTransitionBody(t);
      }
    }

    if (transitions.some((t) => t.condition)) {
      this.line(`}`);
    }

    this.indent--;
    this.line(`}`);
    this.emitBlank();
  }

  private emitTransitionBody(transition: TransitionDef): void {
    if (transition.nextState) {
      const targetAttr = toCamelCase(`state_${toSnakeCase(transition.nextState)}`);
      let transName = transition.event;
      if (transition.condition) transName = `${transition.event}[${transition.condition}]`;

      this.line(
        `TransitionHelper.processTransitionBegin(context, this, (context as any).${targetAttr}, "${transName}");`,
      );
      for (const action of transition.actions ?? []) {
        this.emitAction(action, "context");
      }
      this.line(`(context as any).stateCurrent = (context as any).${targetAttr};`);
      this.line(`TransitionHelper.processTransitionEnd(context, this, (context as any).${targetAttr});`);
    } else {
      for (const action of transition.actions ?? []) {
        this.emitAction(action, "context");
      }
    }
  }

  private emitContextClass(): void {
    const name = this.settings.name ?? "StateMachine";
    const base = this.settings.asynchronous ? "ContextAsync" : "Context";
    const ctxName = this.settings.context?.class ?? `${name}Context`;

    this.line(`export class ${ctxName} extends ${base} {`);
    this.indent++;

    // State fields
    for (const state of this.model.allStates) {
      if (state.kind === "history") continue;
      const attr = toCamelCase(`state_${toSnakeCase(state.name)}`);
      const className = this.isLeaf(state)
        ? `State${toClassName(state.name)}`
        : "State";
      this.line(`${attr}!: ${className};`);
    }

    // Object fields
    for (const obj of this.settings.objects ?? []) {
      this.line(`${obj.instance}: ${tsType(obj.class)};`);
    }
    this.emitBlank();

    // Constructor
    const objParams = (this.settings.objects ?? [])
      .map((o) => `${o.instance}: ${tsType(o.class)}`)
      .join(", ");

    this.line(`constructor(${objParams}) {`);
    this.indent++;
    this.line(`super("${ctxName}");`);
    for (const obj of this.settings.objects ?? []) {
      this.line(`this.${obj.instance} = ${obj.instance};`);
    }
    this.emitBlank();

    // Init non-leaf states
    for (const state of this.model.allStates) {
      if (state.kind === "history" || this.isLeaf(state)) continue;
      const attr = toCamelCase(`state_${toSnakeCase(state.name)}`);
      const parentName = this.model.parentMap.get(state.name);
      const parentRef = parentName ? `this.${toCamelCase(`state_${toSnakeCase(parentName)}`)}` : "null";
      const kind = parentName === null ? "StateKind.ROOT" : "StateKind.COMPOSITE";
      this.line(`this.${attr} = new State("${state.name}", ${kind}, ${parentRef});`);
    }

    // Init leaf states
    for (const state of this.model.allStates) {
      if (state.kind === "history" || !this.isLeaf(state)) continue;
      const attr = toCamelCase(`state_${toSnakeCase(state.name)}`);
      const className = `State${toClassName(state.name)}`;
      const parentName = this.model.parentMap.get(state.name);
      const parentRef = parentName ? `this.${toCamelCase(`state_${toSnakeCase(parentName)}`)}` : "null";
      this.line(`this.${attr} = new ${className}(${parentRef});`);
    }

    this.indent--;
    this.line(`}`);
    this.emitBlank();

    // enterInitialState
    const initialLeaf = this.findInitialLeaf(this.model.definition.state);
    if (initialLeaf) {
      const attr = toCamelCase(`state_${toSnakeCase(initialLeaf.name)}`);
      this.line(`enterInitialState(): void {`);
      this.indent++;
      this.line(`this.stateCurrent = this.${attr};`);
      const chain = this.buildEntryChain(initialLeaf);
      for (const s of chain) {
        const sAttr = toCamelCase(`state_${toSnakeCase(s.name)}`);
        this.line(`this.observer.onEntry(this.name, "${s.name}");`);
        this.line(`this.${sAttr}.onEntry(this);`);
      }
      this.indent--;
      this.line(`}`);
      this.emitBlank();
    }

    // setState
    this.line(`setState(stateName: string): void {`);
    this.indent++;
    this.line(`const stateMap: Record<string, State> = {`);
    this.indent++;
    for (const state of this.model.allStates) {
      if (state.kind === "history" || !this.isLeaf(state)) continue;
      const attr = toCamelCase(`state_${toSnakeCase(state.name)}`);
      this.line(`"${state.name}": this.${attr},`);
    }
    this.indent--;
    this.line(`};`);
    this.line(`if (stateName in stateMap) this.stateCurrent = stateMap[stateName];`);
    this.indent--;
    this.line(`}`);
    this.emitBlank();

    // Event handler methods
    for (const [evtId, evt] of this.model.eventMap) {
      const methodName = `on${toPascalCase(toSnakeCase(evtId))}`;
      const params = this.buildParams(evt, false);
      const callArgs = (evt.parameters ?? []).map((p) => toCamelCase(p.name)).join(", ");

      this.line(`${methodName}(${params}): void {`);
      this.indent++;
      this.line(`if (this.stateCurrent) {`);
      this.indent++;
      const args = callArgs ? `this, ${callArgs}` : "this";
      this.line(`(this.stateCurrent as any).${methodName}(${args});`);
      this.indent--;
      this.line(`}`);
      this.indent--;
      this.line(`}`);
      this.emitBlank();
    }

    this.indent--;
    this.line(`}`);
  }

  private emitFeederClasses(): void {
    for (const [feederName, events] of this.model.feedersMap) {
      this.emitFeederClass(feederName, events);
      this.emitBlank();
    }
  }

  private emitFeederClass(feederName: string, events: EventDef[]): void {
    const name = this.settings.name ?? "StateMachine";
    const ctxName = this.settings.context?.class ?? `${name}Context`;

    this.line(`export class ${feederName} {`);
    this.indent++;
    this.line(`private context: ${ctxName};`);
    this.emitBlank();
    this.line(`constructor(context: ${ctxName}) {`);
    this.indent++;
    this.line(`this.context = context;`);
    this.indent--;
    this.line(`}`);
    this.emitBlank();

    for (const evt of events) {
      const methodName = toCamelCase(toSnakeCase(evt.id));
      const params = this.buildParams(evt, false);
      const callArgs = (evt.parameters ?? []).map((p) => toCamelCase(p.name)).join(", ");
      const ctxMethod = `on${toPascalCase(toSnakeCase(evt.id))}`;

      this.line(`${methodName}(${params}): void {`);
      this.indent++;
      if (this.settings.asynchronous) {
        this.line(
          `this.context.scheduleEvent(this.context.${ctxMethod}.bind(this.context)${callArgs ? ", " + callArgs : ""});`,
        );
      } else {
        this.line(`this.context.${ctxMethod}(${callArgs});`);
      }
      this.indent--;
      this.line(`}`);
      this.emitBlank();
    }

    this.indent--;
    this.line(`}`);
  }

  // --- Helpers ---

  private emitAction(action: ActionDef, ctxVar: string): void {
    if (action.code) {
      this.line(`(${ctxVar} as any).${action.code};`);
    } else if (action.timerStart) {
      const timer = action.timerStart.timer;
      const duration = action.timerStart.duration;
      const evtMethod = `on${toPascalCase(toSnakeCase(timer))}`;
      this.line(
        `${ctxVar}.startTimer("${timer}", ${duration}, () => (${ctxVar} as any).${evtMethod}());`,
      );
    } else if (action.timerStop) {
      this.line(`${ctxVar}.stopTimer("${action.timerStop}");`);
    }
  }

  private buildParams(evt: EventDef, includeContext: boolean): string {
    const parts: string[] = [];
    if (includeContext) parts.push("context: ContextBase");
    for (const p of evt.parameters ?? []) {
      parts.push(`${toCamelCase(p.name)}: ${tsType(p.type)}`);
    }
    return parts.join(", ");
  }

  private isLeaf(state: StateDef): boolean {
    return !(state.states?.length) && !state.parallel;
  }

  private findInitialLeaf(state: StateDef): StateDef | null {
    if (this.isLeaf(state)) return state;
    if (state.states?.length) return this.findInitialLeaf(state.states[0]);
    return null;
  }

  private buildEntryChain(state: StateDef): StateDef[] {
    const chain: StateDef[] = [];
    let name: string | null | undefined = state.name;
    while (name) {
      const s = this.model.stateMap.get(name);
      if (s) chain.push(s);
      name = this.model.parentMap.get(name) ?? undefined;
    }
    return chain.reverse();
  }

  private line(text: string): void {
    this.lines.push("  ".repeat(this.indent) + text);
  }

  private emitBlank(): void {
    this.lines.push("");
  }
}
